// Code generated by goctl. DO NOT EDIT!
// Source: api-user.proto

package apiuserclient

import (
	"context"

	"store/rpc-user/apiuser"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	GetUserReq    = apiuser.GetUserReq
	GetUserRes    = apiuser.GetUserRes
	User          = apiuser.User
	UpdateUserReq = apiuser.UpdateUserReq
	Response      = apiuser.Response
	RegisterReq   = apiuser.RegisterReq
	NullRes       = apiuser.NullRes
	UpdateUserRes = apiuser.UpdateUserRes
	LoginReq      = apiuser.LoginReq
	LoginRes      = apiuser.LoginRes

	ApiUser interface {
		//   注册接口
		Register(ctx context.Context, in *RegisterReq) (*NullRes, error)
		//   登录接口
		Login(ctx context.Context, in *LoginReq) (*LoginRes, error)
		//   获取用户信息
		GetUser(ctx context.Context, in *GetUserReq) (*GetUserRes, error)
		//   更新用户信息
		UpdateUser(ctx context.Context, in *UpdateUserReq) (*UpdateUserRes, error)
	}

	defaultApiUser struct {
		cli zrpc.Client
	}
)

func NewApiUser(cli zrpc.Client) ApiUser {
	return &defaultApiUser{
		cli: cli,
	}
}

//   注册接口
func (m *defaultApiUser) Register(ctx context.Context, in *RegisterReq) (*NullRes, error) {
	client := apiuser.NewApiUserClient(m.cli.Conn())
	return client.Register(ctx, in)
}

//   登录接口
func (m *defaultApiUser) Login(ctx context.Context, in *LoginReq) (*LoginRes, error) {
	client := apiuser.NewApiUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

//   获取用户信息
func (m *defaultApiUser) GetUser(ctx context.Context, in *GetUserReq) (*GetUserRes, error) {
	client := apiuser.NewApiUserClient(m.cli.Conn())
	return client.GetUser(ctx, in)
}

//   更新用户信息
func (m *defaultApiUser) UpdateUser(ctx context.Context, in *UpdateUserReq) (*UpdateUserRes, error) {
	client := apiuser.NewApiUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in)
}
